### PR TITLE
add backend variable

### PR DESCRIPTION
**Pull request by migrae**
localhost is now BACKEND

### CODE REVIEW

**Comment by fsandel** [comment]
Seems like it doesnt work yet, still get redirected to localhost when trying to login from a different url

**Review by fsandel — CHANGES_REQUESTED** [review]
Still get redirected to localhost when trying to use the intra login from another url

**Comment by migrae** [comment]
fixed.
but no more "secure" cookies until we switch to https

**Review by fsandel — APPROVED** [review]
:shipit:

**Pull request merged**
